-- ===========================================================================
-- 0003_funnel_seed.sql · Revenue Radar — checkout-funnel SEED baseline
--   GENERATED by scripts/seed-funnel.mjs (deterministic, seed=20260625). DO NOT hand-edit.
--   Shape = src/services/funnel/contract.ts. Target: Cloudflare D1 (SQLite, STRICT).
--
--   Two tables:
--     funnel_seed — persistent per-(brand,cohort,stage) baseline ("representative day").
--     funnel_live — resettable live layer (traffic simulator + amplify-on-action).
--   Funnel total = funnel_seed + funnel_live + real Coach demo_events. The 'all' cohort
--   is NOT stored — the compute layer sums the real cohorts (gen_z/millennial/gen_x/boomer).
--
--   Stories (hand-tuned so leaks read cleanly):
--     Coach           — HERO: gen_z add_payment_info -> purchase ~0.55 (BNPL hesitation).
--     Kate Spade      — view_cart -> begin_checkout ~0.55 (Empty-Cart Viewers).
--     Stuart Weitzman — begin_checkout -> add_shipping_info ~0.58 (shipping sticker-shock).
--
--   Apply (LOCAL then REMOTE):
--     npx wrangler d1 migrations apply coach-demo-db --local
--     npx wrangler d1 migrations apply coach-demo-db --remote
-- ===========================================================================

-- ── Schema (STRICT). IF NOT EXISTS so re-apply is safe. ──
CREATE TABLE IF NOT EXISTS funnel_seed (
  brand    TEXT,
  cohort   TEXT,
  stage    TEXT,
  sessions INTEGER,
  PRIMARY KEY (brand, cohort, stage)
) STRICT;

CREATE TABLE IF NOT EXISTS funnel_live (
  brand      TEXT,
  cohort     TEXT,
  stage      TEXT,
  sessions   INTEGER NOT NULL DEFAULT 0,
  updated_ts INTEGER,
  PRIMARY KEY (brand, cohort, stage)
) STRICT;

-- Helpful indexes (the PK already covers brand / brand,cohort prefix lookups).
CREATE INDEX IF NOT EXISTS idx_funnel_seed_brand_stage ON funnel_seed(brand, stage);
CREATE INDEX IF NOT EXISTS idx_funnel_live_brand_stage ON funnel_live(brand, stage);
CREATE INDEX IF NOT EXISTS idx_funnel_live_updated     ON funnel_live(updated_ts);

-- Idempotent re-seed of the baseline ONLY (never touches the live layer).
DELETE FROM funnel_seed;

-- Coach — HERO leak — gen_z add_payment_info -> purchase collapses (~0.55 vs ~0.78): Gen-Z BNPL hesitation on high-AOV bags. Other cohorts near baseline.
INSERT INTO funnel_seed (brand, cohort, stage, sessions) VALUES
  ('Coach', 'gen_z', 'add_to_cart', 893),
  ('Coach', 'gen_z', 'view_cart', 736),
  ('Coach', 'gen_z', 'begin_checkout', 503),
  ('Coach', 'gen_z', 'add_shipping_info', 373),
  ('Coach', 'gen_z', 'add_payment_info', 298),
  ('Coach', 'gen_z', 'purchase', 166),
  ('Coach', 'millennial', 'add_to_cart', 1081),
  ('Coach', 'millennial', 'view_cart', 898),
  ('Coach', 'millennial', 'begin_checkout', 605),
  ('Coach', 'millennial', 'add_shipping_info', 455),
  ('Coach', 'millennial', 'add_payment_info', 365),
  ('Coach', 'millennial', 'purchase', 281),
  ('Coach', 'gen_x', 'add_to_cart', 604),
  ('Coach', 'gen_x', 'view_cart', 492),
  ('Coach', 'gen_x', 'begin_checkout', 339),
  ('Coach', 'gen_x', 'add_shipping_info', 256),
  ('Coach', 'gen_x', 'add_payment_info', 203),
  ('Coach', 'gen_x', 'purchase', 157),
  ('Coach', 'boomer', 'add_to_cart', 390),
  ('Coach', 'boomer', 'view_cart', 320),
  ('Coach', 'boomer', 'begin_checkout', 219),
  ('Coach', 'boomer', 'add_shipping_info', 165),
  ('Coach', 'boomer', 'add_payment_info', 133),
  ('Coach', 'boomer', 'purchase', 104);

-- Kate Spade — Empty-Cart Viewers — view_cart -> begin_checkout weak (~0.55) across all cohorts: cart does not persist.
INSERT INTO funnel_seed (brand, cohort, stage, sessions) VALUES
  ('Kate Spade', 'gen_z', 'add_to_cart', 901),
  ('Kate Spade', 'gen_z', 'view_cart', 740),
  ('Kate Spade', 'gen_z', 'begin_checkout', 412),
  ('Kate Spade', 'gen_z', 'add_shipping_info', 313),
  ('Kate Spade', 'gen_z', 'add_payment_info', 249),
  ('Kate Spade', 'gen_z', 'purchase', 195),
  ('Kate Spade', 'millennial', 'add_to_cart', 1091),
  ('Kate Spade', 'millennial', 'view_cart', 904),
  ('Kate Spade', 'millennial', 'begin_checkout', 497),
  ('Kate Spade', 'millennial', 'add_shipping_info', 378),
  ('Kate Spade', 'millennial', 'add_payment_info', 298),
  ('Kate Spade', 'millennial', 'purchase', 232),
  ('Kate Spade', 'gen_x', 'add_to_cart', 595),
  ('Kate Spade', 'gen_x', 'view_cart', 483),
  ('Kate Spade', 'gen_x', 'begin_checkout', 262),
  ('Kate Spade', 'gen_x', 'add_shipping_info', 196),
  ('Kate Spade', 'gen_x', 'add_payment_info', 155),
  ('Kate Spade', 'gen_x', 'purchase', 121),
  ('Kate Spade', 'boomer', 'add_to_cart', 411),
  ('Kate Spade', 'boomer', 'view_cart', 342),
  ('Kate Spade', 'boomer', 'begin_checkout', 190),
  ('Kate Spade', 'boomer', 'add_shipping_info', 143),
  ('Kate Spade', 'boomer', 'add_payment_info', 114),
  ('Kate Spade', 'boomer', 'purchase', 90);

-- Stuart Weitzman — Shipping sticker-shock — begin_checkout -> add_shipping_info weak (~0.58) across all cohorts: highest-AOV brand.
INSERT INTO funnel_seed (brand, cohort, stage, sessions) VALUES
  ('Stuart Weitzman', 'gen_z', 'add_to_cart', 921),
  ('Stuart Weitzman', 'gen_z', 'view_cart', 746),
  ('Stuart Weitzman', 'gen_z', 'begin_checkout', 500),
  ('Stuart Weitzman', 'gen_z', 'add_shipping_info', 294),
  ('Stuart Weitzman', 'gen_z', 'add_payment_info', 232),
  ('Stuart Weitzman', 'gen_z', 'purchase', 181),
  ('Stuart Weitzman', 'millennial', 'add_to_cart', 1080),
  ('Stuart Weitzman', 'millennial', 'view_cart', 875),
  ('Stuart Weitzman', 'millennial', 'begin_checkout', 586),
  ('Stuart Weitzman', 'millennial', 'add_shipping_info', 340),
  ('Stuart Weitzman', 'millennial', 'add_payment_info', 270),
  ('Stuart Weitzman', 'millennial', 'purchase', 211),
  ('Stuart Weitzman', 'gen_x', 'add_to_cart', 605),
  ('Stuart Weitzman', 'gen_x', 'view_cart', 502),
  ('Stuart Weitzman', 'gen_x', 'begin_checkout', 339),
  ('Stuart Weitzman', 'gen_x', 'add_shipping_info', 197),
  ('Stuart Weitzman', 'gen_x', 'add_payment_info', 159),
  ('Stuart Weitzman', 'gen_x', 'purchase', 123),
  ('Stuart Weitzman', 'boomer', 'add_to_cart', 401),
  ('Stuart Weitzman', 'boomer', 'view_cart', 325),
  ('Stuart Weitzman', 'boomer', 'begin_checkout', 218),
  ('Stuart Weitzman', 'boomer', 'add_shipping_info', 124),
  ('Stuart Weitzman', 'boomer', 'add_payment_info', 99),
  ('Stuart Weitzman', 'boomer', 'purchase', 76);


-- ── Verify (every brand shows 6 stages; sessions non-increasing down the funnel) ──
--   SELECT brand, stage, SUM(sessions) AS sessions
--     FROM funnel_seed GROUP BY brand, stage
--    ORDER BY brand, CASE stage
--      WHEN 'add_to_cart' THEN 1 WHEN 'view_cart' THEN 2 WHEN 'begin_checkout' THEN 3
--      WHEN 'add_shipping_info' THEN 4 WHEN 'add_payment_info' THEN 5 WHEN 'purchase' THEN 6 END;
-- ===========================================================================
-- END 0003_funnel_seed.sql
-- ===========================================================================
