// src/content/decide.ts
// The decision, pure. Given the catalog, the page's slots, the shopper's
// affinity, the cell, the arm and the versions in force, produce the delivery
// contract and the ledger records in one pass. No I/O, no clock, no randomness:
// the same input yields the same output, which is what makes replay (doc 22
// §12.3) a proof rather than a hope.

import { composeContentDetailed, HISTORICAL_PINS, HISTORICAL_GOVERNANCE, HISTORICAL_GOVERNANCE_V1, type HistoricalPins, type HistoricalGovernance, type ContentPieceLike, type ContentSlotSpec, type AffinityViewLike, type ScoreAdjust } from '@/reflex/contentCompose';
import type {
  Arm, Authority, Cell, ConstraintDiagnostic, ConstraintDiagnostics, ContentDecisionSet, ContentPiece, DecisionRecord, DecisionVersions, IdentityAnchor, LiftApplied, RegionalBlend, SeedDiagnostic, SeedDriver, SeedRule, SlotStrategy,
} from './types';
import { validateSeedRules } from './kinds';
import { arrivedFromNetwork, type ChannelSignals } from '@/services/visit';
import { isEligibleAt, type EligibilityContext } from './lifecycle';
import { liftFor, type LiftSnapshot } from '@/learn/stats';
import { explorationPick, HISTORICAL_EXPLORATION, type ExploreConfig, type ExplorePick } from '@/learn/explore';
import { merchandisingAdjustDetailed, merchandisingSentence, type MerchandisingResult } from '@/reflex/merchandising';
import type { DecisionInputs, ExternalTerm, ItemControl, StageRule, StageWord } from './types';
import { STAGE_WORDS } from '@/services/JourneyStage';
import { isEventNonce, isEventTimestamp } from '@/events/actionTypes';
import { HISTORICAL_CONTENT_TYPES, withContentTypeAffinity } from './typeAffinity';
import { compileSlotConstraints, rankedCapacity } from './slotConstraints';

export interface DecideInput {
  tenant: string;
  brand: string;
  page: string;
  visitorId: string;
  sessionId: string | null;
  identityAnchor: IdentityAnchor;
  nowMs: number;
  /** Supplied by the I/O producer, never generated by this pure decision. */
  requestId?: string;
  pieces: readonly ContentPiece[];
  slots: readonly SlotStrategy[];
  /** Internal replay execution bound; all slots still participate in reservations. */
  replayRankingSlots?: ReadonlySet<string>;
  affinity: AffinityViewLike | null;
  /**
   * The population prior already blended into `affinity` by the service, with
   * the regional shares it used, so each decision can itemize what the region
   * contributed. Null when no prior applied.
   */
  regional?: (RegionalBlend & { share: Readonly<Record<string, Readonly<Record<string, number>>>> }) | null;
  cell: Cell;
  /**
   * Where and under what conditions this request is happening, for the pieces
   * that carry an `eligibleWhen` rule (Garrett's "snowing in the Pacific
   * Northwest"). Absent means no rule can pass, which leaves every catalog
   * without rules behaving exactly as before.
   */
  eligibility?: EligibilityContext;
  arm: Arm;
  versions: DecisionVersions;
  configLabel: string;
  /** Top-N candidates recorded per slot (doc 22 §3.1). */
  candidateLimit?: number;
  /**
   * The learning layer (doc 22 §6): per slot, the lift snapshot in force and the
   * trust dial. At γ = 0 the lift is computed, shown on the receipt, and ignored.
   */
  learning?: {
    snapshots: Record<string, LiftSnapshot | null>;
    gammaOf: (slot: string) => number;
    /** Doc 22 §7, per slot; absent means off. */
    exploreOf?: (slot: string) => ExploreConfig | null;
    /** Doc 22 §12.2, per slot: a merchandiser's control over an item's learned lift. */
    controlOf?: (slot: string, item: string) => ItemControl | null;
    /** Pinned slot authority, including when a compatible lift is unavailable. */
    metadataOf?: (slot: string) => { reward: import('@/ledger/records').RewardType; objective?: 'unit' | 'revenue' | 'margin'; measurementBasis?: import('./types').MeasurementBasis };
  } | null;
  /** Doc 22 §9: their model's answer for this page, or why there is none. Null when no model is configured. */
  external?: ExternalTerm | null;
  /** CW30: slot → item → times served to this visitor inside the slot's fatigue window, from the ring. Null when not read. */
  served?: Record<string, Record<string, number>> | null;
  /**
   * W16 C3: the arrival this page load reports, for the contextual seed rules
   * that read the campaign term and the referrer network. The entry-channel
   * signal is read from the cell, which already carries the established owned
   * channel (R13). Observed context only: it is never stored by this decision.
   */
  entry?: ChannelSignals;
}

const NO_SIGNAL: AffinityViewLike = { dims: {} };

/** The sample bound both existing advisory channels carry; the count stays whole. */
const CONSTRAINT_WARNING_SAMPLE = 50;

/**
 * What a page's published hard slot controls actually cost it: per slot, the
 * pieces that slot could otherwise have served and the published pair that
 * refused each. Today the composer computes the refusal and drops it on the
 * floor for every piece that is not a pin, so a merchandiser cannot tell a
 * market exclusion from a missing piece or an exhausted take.
 *
 * Pure, and read from the same compiled gates and the same eligible pieces the
 * composer ranks, so it can never disagree with what was served. Advisory only:
 * it changes no ranking, no eligibility, no record and nothing stored.
 *
 * DISCRIMINATED: only a piece that was otherwise eligible for that slot — live,
 * inside its window and in stock, and naming the slot identifier in its own
 * `slotTypes` — is named, because a piece the slot could never have served was
 * not refused by the constraint. Only a slot the composer actually RANKS
 * contributes at all: an off-limits slot and a slot whose take is a
 * non-personalizable pin consider no candidate, so they refuse nobody however
 * many exclusions they publish, and a dormant or refused pin already has its
 * own home in `slot-pin-diagnostics/v1`. BOUNDED: every refused eligible piece
 * is counted, at most the first `CONSTRAINT_WARNING_SAMPLE` are carried (slot
 * order, then catalogue order) and the remainder is reported as omitted.
 */
function constraintDiagnosticsFor(eligible: readonly ContentPiece[], specs: readonly ContentSlotSpec[],
  ranks: (spec: ContentSlotSpec) => boolean, historicalGovernance?: HistoricalGovernance): ConstraintDiagnostics | null {
  // A retained receipt decided before the hard controls existed is replayed
  // without them, so there is no refusal of theirs to name either.
  if (historicalGovernance === HISTORICAL_GOVERNANCE) return null;
  const warnings: ConstraintDiagnostic[] = [];
  let warningCount = 0;
  for (const spec of specs) {
    if (!ranks(spec)) continue;
    const gate = compileSlotConstraints(spec, historicalGovernance !== HISTORICAL_GOVERNANCE_V1);
    if (!gate.active) continue;
    for (const piece of eligible) {
      if (!piece.slotTypes.includes(spec.slot)) continue;
      const refusal = gate.refusal(piece);
      if (!refusal) continue;
      warningCount++;
      if (warnings.length < CONSTRAINT_WARNING_SAMPLE) {
        warnings.push({ slot: spec.slot, contentId: piece.id, reason: refusal.reason,
          ...(refusal.dimension === undefined ? {} : { dimension: refusal.dimension }),
          ...(refusal.value === undefined ? {} : { value: refusal.value }) });
      }
    }
  }
  return warningCount ? { warningCount, omittedWarningCount: warningCount - warnings.length, warnings } : null;
}

/** Three decimals, the grain every itemised delta on a receipt is recorded at. */
const r3 = (n: number): number => { const v = Math.round(n * 1000) / 1000; return v === 0 ? 0 : v; };

const authorityOf = (strategy: string): Authority =>
  strategy === 'tenant-pinned' ? 'pin' : strategy === 'default' ? 'default' : 'engine';

export function decideContent(i: DecideInput, historical?: typeof HISTORICAL_EXPLORATION, historicalPins?: HistoricalPins,
  historicalContentTypes?: typeof HISTORICAL_CONTENT_TYPES, historicalGovernance?: HistoricalGovernance): ContentDecisionSet {
  const hasNonce = Object.prototype.hasOwnProperty.call(i, 'requestId');
  if (hasNonce && (!isEventNonce(i.requestId) || !isEventTimestamp(i.nowMs))) throw new Error('Invalid decision identity');
  // The `default` arm is the site's own defaults: no personalization, so the
  // composer sees no signal. Pins still apply — they are merchandising
  // authority, not personalization, and the holdout must not remove them.
  const affinity = i.arm === 'default' ? NO_SIGNAL : (i.affinity ?? NO_SIGNAL);
  const specs: ContentSlotSpec[] = i.slots.map((s) => ({
    slot: s.slot, take: s.take, weights: s.weights,
    ...(s.pinnedPieceId ? { pinnedPieceId: s.pinnedPieceId } : {}),
    ...(!historicalPins && s.pinnedPieceIds ? { pinnedPieceIds: [...s.pinnedPieceIds] } : {}),
    ...(s.offLimits !== undefined ? { offLimits: s.offLimits } : {}),
    ...(s.excludedPieceIds ? { excludedPieceIds: s.excludedPieceIds } : {}),
    ...(s.excludedTags ? { excludedTags: s.excludedTags } : {}),
    ...(s.allowedTypes ? { allowedTypes: s.allowedTypes } : {}),
    // CW33: the slot's diversity rule, applied by the composer at the take.
    ...(s.diversity ? { diversity: s.diversity } : {}),
  }));
  // Eligibility before scoring: outside its publish window, or out of stock (CW33), a piece does not
  // exist for this decision, however well it would have scored.
  // Keep the site's default diversity/order unchanged as well as its zero scores.
  const projectTypes = i.arm !== 'default' && historicalContentTypes !== HISTORICAL_CONTENT_TYPES;
  const eligible: ContentPiece[] = [], byId = new Map<string, ContentPiece>();
  for (const original of i.pieces) {
    const piece = projectTypes ? withContentTypeAffinity(original) : original;
    byId.set(piece.id, piece);
    if (isEligibleAt(piece, i.nowMs, i.eligibility)) eligible.push(piece);
  }

  // The learning layer: lift^γ on the base score, looked up at the finest level
  // with enough evidence for this item in this cell. The base and the lift are
  // both kept so the receipt shows the arithmetic, not only its result.
  const baseOf = new Map<string, number>();
  const liftOf = new Map<string, LiftApplied>();
  // Doc 22 §10: `default` sees no personalization at all; `no_learning` is personalized with γ = 0 and
  // no exploration, the arm that separates what stage one contributes from what stage two adds.
  const learning = i.arm === 'default' ? null : i.arm === 'no_learning' && i.learning ? { ...i.learning, gammaOf: () => 0, exploreOf: undefined } : i.learning ?? null;
  // Phase 3 (doc 22 §9): their model's term, w_ext × score, added to the base
  // score before the lift and itemized like every other driver.
  const ext = i.arm === 'default' ? null : i.external ?? null;
  const extOf = new Map<string, { score: number; weight: number; contribution: number }>();
  // Scope §1.5 (ledger 20 row 6): season, promotion and margin as clamped multipliers on the
  // merchandised base, after affinity and their model, before the lift. Item properties only, so
  // they apply on every arm; each term is itemised as the delta it caused. The weights live on the
  // slot strategy, the signals on the piece, so a replay reproduces them from the documents.
  const merchWeights = new Map(i.slots.map((s) => [s.slot, s.merchandising ?? null]));
  const hasMerch = [...merchWeights.values()].some((w) => w && (['season', 'promotion', 'margin'] as const).some((t) => (w[t] ?? 0) !== 0));
  const merchDetailed = merchandisingAdjustDetailed<ContentPiece>({ weightsForSlot: (slot) => merchWeights.get(slot) ?? null, signalsOf: (p) => p.merchandising ?? null });
  const merchOf = new Map<string, MerchandisingResult>();
  // CW29 (BTIE A.3.4): the slot's journey-stage rule. The visitor's stage is on the cell, the piece's
  // fit on the piece, the dials on the slot; a piece outside the stage is multiplied down, a piece
  // inside it gets the bonus. Personalization, so never on the default arm, and off when the stage is
  // unknown: an unknown stage is recorded as such, never guessed, and a guess would demote by accident.
  const visitorStage: StageWord | null = i.arm !== 'default' && i.cell.stage && i.cell.stage !== 'unknown' ? STAGE_WORDS[i.cell.stage] : null;
  const stageRules = new Map<string, StageRule>(i.slots.flatMap((s) => (s.stage && ((s.stage.outOfStage ?? 1) < 1 || (s.stage.inStage ?? 0) > 0) ? [[s.slot, s.stage] as const] : [])));
  const hasStage = visitorStage !== null && stageRules.size > 0;
  const stageOf = new Map<string, { visitor: StageWord; fit: StageWord[]; applied: number; inside: boolean }>();
  // CW30 (BTIE D2): freshness and fatigue. Recent content gets a bonus that halves every `halfLifeDays`
  // from the piece's freshness date; content this visitor was already served gets a penalty that grows
  // with the count in the ring up to `cap`. The engine's judgment, so not on the default arm; both
  // itemised as the delta they caused. The served counts travel on the record's inputs for the replay.
  const freshRules = new Map(i.slots.flatMap((s) => (s.freshness && s.freshness.weight > 0 ? [[s.slot, s.freshness] as const] : [])));
  const fatigueRules = new Map(i.slots.flatMap((s) => (s.fatigue && s.fatigue.weight > 0 ? [[s.slot, s.fatigue] as const] : [])));
  const hasFresh = i.arm !== 'default' && freshRules.size > 0;
  const hasFatigue = i.arm !== 'default' && fatigueRules.size > 0 && Boolean(i.served);
  const freshOf = new Map<string, { ageDays: number; decay: number; applied: number }>();
  const fatigueOf = new Map<string, { served: number; windowHours: number; applied: number }>();
  const dateOf = (p: ContentPiece): number | null => {
    const v = p.freshnessDate ?? p.window?.from;
    if (!v) return null;
    const t = Date.parse(v);
    return Number.isFinite(t) ? t : null;
  };
  // W16 C3 (document 35 §2 F13): the arrival's own evidence, before the shopper
  // has shown any of her own. The rule set is published on the slot and revalidated
  // here, because a RETAINED document the current contract refuses is ignored
  // WHOLE — half a rule set is a ranking nobody authored — and the refusal is
  // diagnosed rather than fabricated into an influence. Personalization, so never
  // on the holdout's default arm.
  const seedRules = new Map<string, SeedRule[]>();
  const seedDiagnostics: SeedDiagnostic[] = [];
  if (i.arm !== 'default') for (const s of i.slots) {
    if (s.seeds === undefined) continue;
    const checked = validateSeedRules(s.seeds, s.weights);
    if (!checked.ok) { seedDiagnostics.push({ slot: s.slot, reason: 'invalid_rule_set' }); continue; }
    // An empty rule set is the same as none: nothing to seed and nothing to claim.
    if (checked.value.length) seedRules.set(s.slot, checked.value);
  }
  const term = (v: unknown) => (typeof v === 'string' ? v.trim().toLowerCase() : '');
  const arrivalTerm = term(i.entry?.utmTerm);
  const fires = (rule: SeedRule): boolean =>
    rule.signal === 'entry_channel' ? i.cell.channel === rule.value
      : rule.signal === 'campaign_term' ? arrivalTerm !== '' && arrivalTerm === term(rule.value)
        : arrivedFromNetwork(i.entry, rule.value);
  const weightsOf = new Map(i.slots.map((s) => [s.slot, s.weights]));
  /** The rules this arrival fired for this candidate, each at `rule.weight × the slot's weight for the tag's dimension`. */
  const seedDriversFor = (p: ContentPieceLike, slot: string): SeedDriver[] => {
    const rules = seedRules.get(slot), weights = weightsOf.get(slot);
    if (!rules || !weights) return [];
    const piece = byId.get(p.id) ?? (p as ContentPiece);
    const drivers: SeedDriver[] = [];
    for (const rule of rules) {
      if (!fires(rule)) continue;
      for (const tag of rule.tags) {
        const w = weights[tag.dimension] ?? 0;
        if (!w || !(piece.tags[tag.dimension] ?? []).includes(tag.value)) continue;
        drivers.push({ signal: rule.signal, value: rule.value, dimension: tag.dimension, tag: tag.value, weight: rule.weight, contribution: r3(rule.weight * w) });
      }
    }
    return drivers;
  };
  const seedOf = new Map<string, NonNullable<DecisionRecord['explain']['contextual']>>();
  /**
   * Everything between the tag sum and the learned lift, in the order the engine
   * applies it. Run with `record` false it is a pure arithmetic probe: the same
   * chain without the seeds, so what the seeds contributed can be measured where
   * it lands — in the final pre-lift base, after merchandising — rather than
   * asserted from where it entered.
   */
  const preLift = (p: ContentPieceLike, slot: string, base0: number, record: boolean): number => {
    const key = `${slot}:${p.id}`;
    let base = base0;
    if (ext && ext.status === 'ok') {
      const w = ext.weightOf(slot), s = ext.scores[p.id];
      if (w > 0 && typeof s === 'number') { base += w * s; if (record) extOf.set(key, { score: s, weight: w, contribution: r3(w * s) }); }
    }
    if (hasStage) {
      const rule = stageRules.get(slot), fit = (byId.get(p.id) ?? (p as ContentPiece)).journeyStageFit;
      if (rule && fit && fit.length) {
        const inside = fit.includes(visitorStage!);
        const before = base;
        if (inside) base += rule.inStage ?? 0; else base *= rule.outOfStage ?? 1;
        const applied = r3(base - before);
        if (record && (applied !== 0 || (!inside && (rule.outOfStage ?? 1) < 1))) stageOf.set(key, { visitor: visitorStage!, fit, applied, inside });
      }
    }
    if (hasFresh) {
      const rule = freshRules.get(slot), at = dateOf(byId.get(p.id) ?? (p as ContentPiece));
      if (rule && at !== null && i.nowMs >= at) {
        const ageDays = (i.nowMs - at) / 86_400_000;
        const decay = Math.pow(2, -ageDays / rule.halfLifeDays);
        const applied = r3(rule.weight * decay);
        if (applied > 0) { base += applied; if (record) freshOf.set(key, { ageDays: Math.round(ageDays * 10) / 10, decay: r3(decay), applied }); }
      }
    }
    if (hasFatigue) {
      const rule = fatigueRules.get(slot), served = i.served?.[slot]?.[p.id] ?? 0;
      if (rule && served > 0) {
        const penalty = rule.weight * Math.min(served, rule.cap) / rule.cap;
        const after = Math.max(0, base - penalty);
        const applied = r3(after - base);
        base = after;
        if (record) fatigueOf.set(key, { served, windowHours: rule.windowHours, applied });
      }
    }
    if (record) baseOf.set(key, base);
    if (hasMerch) {
      // A multiplier on nothing is nothing: a zero base (the default arm, or no signal) gets no block.
      const m = base > 0 ? merchDetailed(byId.get(p.id) ?? (p as ContentPiece), slot, base) : null;
      if (m && m.drivers.length) { if (record) merchOf.set(key, m); base = m.scoreFinal; }
    }
    return base;
  };
  const adjust: ScoreAdjust | undefined = learning || ext || hasMerch || hasStage || hasFresh || hasFatigue || seedRules.size ? (p, slot, base0) => {
    const key = `${slot}:${p.id}`;
    // The seeds enter where the slot's own tag sum lands, before merchandising,
    // because a seed supplies the missing interest for a canonical tag this
    // arrival is evidence for; they are never a global floor.
    const drivers = seedDriversFor(p, slot);
    let seeded = 0;
    for (const d of drivers) seeded += d.contribution;
    const base = preLift(p, slot, base0 + seeded, true);
    if (seedRules.has(slot)) {
      // Measured where it lands: the same chain without the seeds, subtracted. A
      // candidate merchandised to exactly zero records exactly zero, a boost of a
      // half records half, and each driver keeps its share of what was applied.
      const bare = seeded === 0 ? base : preLift(p, slot, base0, false);
      const share = seeded === 0 ? 0 : (base - bare) / seeded;
      seedOf.set(key, { applied: r3(base - bare), drivers: drivers.map((d) => ({ ...d, contribution: r3(d.contribution * share) })) });
    }
    if (!learning) return base;
    const control = learning.controlOf?.(slot, p.id) ?? null;
    if (control) controlOf.set(key, control.mode);
    if (control?.mode === 'reject') return base;                       // learned lift ignored for this item
    const look = liftFor(learning.snapshots[slot], p.id, i.cell);
    const gamma = learning.gammaOf(slot);
    if (control?.mode === 'freeze') {                                   // held at the value a person chose
      const metadata = learning.metadataOf?.(slot) ?? learning.snapshots[slot];
      const lifted = base * Math.pow(control.lift ?? 1, gamma);
      liftOf.set(key, { reward: metadata?.reward ?? 'click', objective: metadata?.objective ?? 'unit', measurementBasis: metadata?.measurementBasis ?? 'served-v1', level: look?.level ?? 0, level_words: 'frozen by a merchandiser', n: look?.n ?? 0, s: look?.s ?? 0, p0: look?.p0 ?? 0, n0: look?.n0 ?? 0, p_hat: look?.p_hat ?? 0, lift: control.lift ?? 1, gamma, applied: r3(lifted - base) });
      return lifted;
    }
    if (!look) return base;
    // N20: what the lift ACTUALLY caused, itemised like every other term. On an
    // exactly zero base a multiplicative term causes nothing, and the receipt
    // must be able to say so instead of claiming an influence there was not.
    const lifted = base * Math.pow(look.lift, gamma);
    liftOf.set(key, { reward: look.reward, objective: look.objective, measurementBasis: look.measurementBasis, level: look.level, level_words: look.level_words, n: look.n, s: look.s, p0: look.p0, n0: look.n0, p_hat: look.p_hat, lift: look.lift, gamma, applied: r3(lifted - base), ...(look.prior ? { prior: look.prior } : {}) });
    return lifted;
  } : undefined;
  const controlOf = new Map<string, 'reject' | 'freeze'>();
  // Exploration (doc 22 §7): decided per slot from the ranked candidates, deterministic in its inputs.
  const explored = new Map<string, ExplorePick>();
  const explore = learning?.exploreOf ? (slot: string, ranked: ReadonlyArray<{ id: string; score: number }>) => {
    const cfg = learning.exploreOf!(slot);
    if (!cfg) return null;
    // W28.M1.01 (F23 §4.3): the merchandiser's item controls belong to the
    // caller, which already holds them, and they govern exploration as well as
    // scoring — an item whose learned treatment a person took control of is out
    // of the rule's discretion. This reads the learn document the decision is
    // already holding: no I/O, nothing that can fail or change the ranking.
    const controlled = new Set<string>();
    if (learning.controlOf) for (const r of ranked) if (learning.controlOf(slot, r.id)) controlled.add(r.id);
    const pick = explorationPick({ visitorId: i.visitorId, slot, nowMs: i.nowMs, ranked, snapshot: learning.snapshots[slot], cfg, controlled }, historical);
    if (!pick) return null;
    explored.set(slot, pick);
    return pick.ranking ? { ranking: pick.ranking } : { first: pick.pieceId };
  } : undefined;
  const { decisions, candidates, pinDiagnostics } = composeContentDetailed(eligible, affinity, specs, i.candidateLimit ?? 10, adjust, explore, historicalPins, historicalGovernance, i.replayRankingSlots);
  const refusedPrefixes = new Set(pinDiagnostics?.filter(d => d.pinIndex !== undefined).map(d => d.slot));
  // The slots the composer ran a ranking for, by its own conditions: capacity
  // left after off-limits and pins (`rankedCapacity`, the composer's `:227` and
  // `:237-250`), a pinned prefix it did not refuse, and — on a replay — the
  // bounded set of slots that re-executed.
  const ranks = (spec: ContentSlotSpec) => rankedCapacity(spec) > 0 && !refusedPrefixes.has(spec.slot)
    && (!i.replayRankingSlots || i.replayRankingSlots.has(spec.slot));
  const constraintDiagnostics = constraintDiagnosticsFor(eligible, specs, ranks, historicalGovernance);
  const specOf = new Map(specs.map((s) => [s.slot, s]));
  // W20 G2 (R86(b), R86(c)): a PINNED slot that served and still could not fill
  // its `take`. Measured from what the composer actually served
  // against the take the document publishes, so it can never disagree with the
  // page. A slot whose pin was refused serves nothing at all and belongs to
  // `pinDiagnostics`, not here; an off-limits slot serves nothing on purpose; a
  // slot a bounded replay did not re-execute never ranked; and a retained
  // receipt decided under the former pin policy is replayed as it was written.
  const shortTakeOf = new Map<string, { take: number; served: number; empty: number; sentence: string }>();
  if (historicalPins !== HISTORICAL_PINS) {
    const refusedSlots = new Set((pinDiagnostics ?? []).map((d) => d.slot));
    const servedIn = new Map<string, number>();
    for (const d of decisions) servedIn.set(d.slot, (servedIn.get(d.slot) ?? 0) + 1);
    for (const spec of specs) {
      const pins = (spec.pinnedPieceIds?.length ?? 0) + (spec.pinnedPieceId ? 1 : 0);
      if (!pins || spec.offLimits || refusedSlots.has(spec.slot)) continue;
      if (i.replayRankingSlots && !i.replayRankingSlots.has(spec.slot)) continue;
      const take = spec.take, served = servedIn.get(spec.slot) ?? 0;
      if (!Number.isSafeInteger(take) || take <= 0 || served >= take) continue;
      const empty = take - served;
      shortTakeOf.set(spec.slot, { take, served, empty,
        sentence: `this pinned slot takes ${take} and served ${served}, so ${empty} position${empty === 1 ? ' was' : 's were'} left to the site's own default` });
    }
  }
  const shortTakes = [...shortTakeOf].map(([slot, block]) => ({ slot, take: block.take, served: block.served, empty: block.empty }));
  // What the region contributed to this decision: Σ over the piece's tags of λ·share·w.
  const regionalOf = (d: { contentId: string; slot: string; strategy?: string }): (RegionalBlend & { contribution: number }) | null => {
    if (!historicalPins && d.strategy === 'tenant-pinned') return null;
    const reg = i.regional; if (!reg || i.arm === 'default') return null;
    const piece = byId.get(d.contentId), spec = specOf.get(d.slot);
    if (!piece || !spec) return null;
    let contribution = 0;
    for (const [dim, values] of Object.entries(piece.tags)) {
      const w = spec.weights[dim] ?? 0; if (!w) continue;
      for (const v of values) contribution += reg.lambda * (reg.share[dim]?.[v] ?? 0) * w;
    }
    if (contribution <= 0) return null;
    const { share: _share, ...summary } = reg;
    return { ...summary, contribution: Math.round(contribution * 1000) / 1000 };
  };
  for (const d of decisions) {
    const r = regionalOf(d);
    if (r) d.explain.drivers.push({ dim: 'regional', value: r.region, a: r.lambda, weight: Math.round((r.contribution / (r.lambda || 1)) * 1000) / 1000 });
    if (ext?.status === 'ok') {
      const e = extOf.get(`${d.slot}:${d.contentId}`);
      if (e) d.explain.drivers.push({ dim: 'external', value: ext.version, a: e.score, weight: e.weight });
    }
    const m = merchOf.get(`${d.slot}:${d.contentId}`);
    if (m) for (const md of m.drivers) d.explain.drivers.push({ dim: 'merchandising', value: md.term, a: md.value, weight: md.weight });
    const st = stageOf.get(`${d.slot}:${d.contentId}`);
    if (st) d.explain.drivers.push({ dim: 'stage', value: st.inside ? `fits ${st.visitor}` : `made for ${st.fit.join(' and ')}, shopper ${st.visitor}`, a: 1, weight: st.applied });
    const fr = freshOf.get(`${d.slot}:${d.contentId}`);
    if (fr) d.explain.drivers.push({ dim: 'freshness', value: `${fr.ageDays} days old`, a: fr.decay, weight: freshRules.get(d.slot)!.weight });
    const fa = fatigueOf.get(`${d.slot}:${d.contentId}`);
    if (fa) d.explain.drivers.push({ dim: 'fatigue', value: `served ${fa.served} time${fa.served === 1 ? '' : 's'} in ${fa.windowHours} h`, a: Math.round(Math.min(fa.served, fatigueRules.get(d.slot)!.cap) / fatigueRules.get(d.slot)!.cap * 1000) / 1000, weight: -fatigueRules.get(d.slot)!.weight });
  }
  const freshSentence = (f: { ageDays: number; decay: number; applied: number }) => `${f.ageDays} days old, freshness at ${f.decay} of new: +${f.applied}`;
  // W26 F1.01 (F21 §6(a)): the count behind this sentence is the shopper's
  // history of this piece ANYWHERE IN THIS BRAND — every placement, every page,
  // either arm (`servedCounts`, src/learn/fan.ts) — and the sentence says the
  // scope it really has. It read "in the last N hours" beside a slot-keyed
  // number and a merchandiser reasonably took it for this slot's own history.
  const fatigueSentence = (f: { served: number; windowHours: number; applied: number }) => `this shopper was served it ${f.served} time${f.served === 1 ? '' : 's'} anywhere in this brand in the last ${f.windowHours} hours: ${f.applied}`;
  const stageSentence = (st: { visitor: StageWord; fit: StageWord[]; applied: number; inside: boolean }) =>
    st.inside ? `made for a shopper who is ${st.visitor}: +${st.applied}` : `made for ${st.fit.join(' and ')}, and this shopper is ${st.visitor}: ${st.applied}`;
  const externalOf = (slot: string, key: string): { external?: DecisionRecord['explain']['external'] } => {
    if (!ext) return {};
    if (ext.status === 'ok') {
      const e = extOf.get(key);
      return e ? { external: { kind: ext.kind, ref: ext.ref, version: ext.version, weight: e.weight, score: e.score, contribution: e.contribution } } : {};
    }
    return ext.weightOf(slot) > 0 ? { external: { kind: ext.kind, ref: ext.ref, status: 'unavailable', reason: ext.reason } } : {};
  };
  // Doc 22 §12.3: what this set was computed from, so a replay is exact.
  const plain = <T,>(v: T): T => JSON.parse(JSON.stringify(v)) as T;
  const inputs: DecisionInputs = {
    affinity: plain(affinity.dims) as DecisionInputs['affinity'],
    replay: {
      version: 1, learning: learning !== null, candidateLimit: i.candidateLimit ?? 10,
      ...(historical === HISTORICAL_EXPLORATION ? {} : { exploration: 'supported-only' as const }),
      ...(historicalPins === HISTORICAL_PINS ? {} : { pins: historicalPins ? 'reserved-eligible-v1' as const : 'prefix-reserved-v2' as const }),
      ...(historicalContentTypes === HISTORICAL_CONTENT_TYPES ? {} : { contentTypes: 'catalog-tags-v1' as const }),
      ...(historicalGovernance === HISTORICAL_GOVERNANCE ? {} : { governance: historicalGovernance === HISTORICAL_GOVERNANCE_V1 ? 'slot-gates-v1' as const : 'slot-gates-v2' as const }),
      slots: i.slots.map((slot) => {
        // Pins bypass scoring and exploration; current pins reserve page ownership.
        const snapshot = slot.pinnedPieceId || (!historicalPins && (refusedPrefixes.has(slot.slot) || rankedCapacity({ ...slot, offLimits: false }) === 0)) || (historicalGovernance !== HISTORICAL_GOVERNANCE && slot.offLimits) ? null : learning?.snapshots[slot.slot];
        return { slot: slot.slot, lift: snapshot?.version ?? 0, prior: snapshot?.priorVersion ?? 0 };
      }),
    },
    ...(i.regional && i.arm !== 'default' ? { regional_share: plain(i.regional.share) as NonNullable<DecisionInputs['regional_share']> } : {}),
    ...(ext?.status === 'ok' ? { external: { version: ext.version, scores: plain(ext.scores) } } : {}),
    ...(hasFatigue && i.served ? { served: plain(i.served) } : {}),
  };

  const positionIn = new Map<string, number>();
  const records: DecisionRecord[] = decisions.map((d) => {
    const position = positionIn.get(d.slot) ?? 0;
    positionIn.set(d.slot, position + 1);
    const regional = regionalOf(d);
    const key = `${d.slot}:${d.contentId}`;
    const lift = liftOf.get(key) ?? null;
    const scoreBase = baseOf.get(key) ?? d.score;
    const pick = explored.get(d.slot);
    const pinned = d.strategy === 'tenant-pinned';
    const rankingPosition = position - (specOf.get(d.slot)?.pinnedPieceIds?.length ?? 0);
    const wasExplored = Boolean(pick && (!historicalPins ? !pinned && rankingPosition === 0 : position === 0) && (pick.ranking ? pick.ranking[0] === d.contentId : pick.pieceId === d.contentId));
    const control = controlOf.get(key);
    return {
      // Tenant first, then time: the R2 partition (brand and hour) is derivable from the id alone,
      // so a support paste resolves without anyone having to remember which brand it came from.
      decision_id: `${i.tenant}:${i.nowMs.toString(36)}:${i.visitorId}:${i.page}:${d.slot}:${position}${hasNonce ? `:n1:${i.requestId}` : ''}`,
      ...(hasNonce ? { request_id: i.requestId } : {}),
      tenant: i.tenant, brand: i.brand, visitor_id: i.visitorId, session_id: i.sessionId, identity_anchor: i.identityAnchor, ts: i.nowMs,
      page: i.page, slot: d.slot, position, item_id: d.contentId, customer_item_id: d.customerContentId,
      ...(!historicalPins && !pinned ? { ranking_position: rankingPosition } : {}),
      candidates: !historicalPins && pinned ? [{ contentId: d.contentId, score: 0 }] : candidates[d.slot] ?? [],
      cell: i.cell, arm: i.arm, explored: wasExplored, authority: authorityOf(d.strategy),
      versions: { ...i.versions, lift: d.strategy === 'tenant-pinned' ? 0 : learning?.snapshots[d.slot]?.version ?? 0, prior: d.strategy === 'tenant-pinned' ? 0 : learning?.snapshots[d.slot]?.priorVersion ?? 0 }, config_label: i.configLabel,
      ...(byId.get(d.contentId)?.featuredProductIds?.length ? { featured_product_ids: [...byId.get(d.contentId)!.featuredProductIds!] } : {}),
      explain: {
        drivers: d.explain.drivers, ...(d.explain.note ? { note: d.explain.note } : {}), score_base: Math.round(scoreBase * 1000) / 1000, ...(regional ? { regional } : {}), lift, score_final: d.score,
        ...(wasExplored && pick ? { exploration: { mode: pick.mode, reason: pick.reason, bucket: pick.bucket, ...(pick.samples ? { sample: pick.samples[d.contentId] } : {}) } } : {}),
        ...(control ? { control } : {}),
        ...(!historicalPins && pinned ? {} : externalOf(d.slot, key)),
        ...(seedOf.has(key) ? { contextual: seedOf.get(key)! } : {}),
        ...(merchOf.has(key) ? { merchandising: (({ boost, clamped, drivers }) => ({ boost, clamped, drivers, sentence: merchandisingSentence(merchOf.get(key)!) }))(merchOf.get(key)!) } : {}),
        ...(stageOf.has(key) ? { stage: (({ visitor, fit, applied }) => ({ visitor, fit, applied, sentence: stageSentence(stageOf.get(key)!) }))(stageOf.get(key)!) } : {}),
        ...(freshOf.has(key) ? { freshness: { ...freshOf.get(key)!, sentence: freshSentence(freshOf.get(key)!) } } : {}),
        ...(fatigueOf.has(key) ? { fatigue: { ...fatigueOf.get(key)!, sentence: fatigueSentence(fatigueOf.get(key)!) } } : {}),
        ...(d.explain.diversity ? { diversity: d.explain.diversity } : {}),
        // W20 G2: the slot fell short of its take, on every record it did write.
        ...(shortTakeOf.has(d.slot) ? { shortTake: { ...shortTakeOf.get(d.slot)! } } : {}),
      },
      inputs,
    };
  });

  return {
    tenant: i.tenant, brand: i.brand, page: i.page, visitor_id: i.visitorId, session_id: i.sessionId, identity_anchor: i.identityAnchor, ts: i.nowMs,
    arm: i.arm, cell: i.cell, versions: { ...i.versions }, config_label: i.configLabel,
    regional: i.regional && i.arm !== 'default' ? (({ share: _s, ...rest }) => rest)(i.regional) : null,
    decisions, records, ...(pinDiagnostics ? { pinDiagnostics } : {}),
    ...(shortTakes.length ? { shortTakes } : {}),
    ...(seedDiagnostics.length ? { seedDiagnostics } : {}),
    ...(constraintDiagnostics ? { constraintDiagnostics } : {}),
  };
}
